[tool.poetry]
name = "cv"
version = "0.1.0"
description = ""
authors = ["刘启明 <455043818@qq.com>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.11"
opencv-python = "^4.9.0.80"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
