name: Release

on:
  push:
    tags:
      - 'v*'

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [macos-latest, windows-latest]

    steps:
      - uses: actions/checkout@v2
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.x' 
      
      - name: Install dependencies
        run: |
          cd python
          python -m pip install --upgrade pip
          pip install pyinstaller

      - name: Build Executable(window)
        if: matrix.os == 'windows-latest'
        run: |
          cd python/RemoveDuplicateImages
          pyinstaller --onefile -y --distpath ../command/win main.py -n RemoveDuplicateImages.exe
      
      - name: Build Executable(mac)
        if: matrix.os == 'macos-latest'
        run: |
          cd python/RemoveDuplicateImages
          pyinstaller --onefile -y --distpath ../command/mac main.py -n RemoveDuplicateImages.exe     
      
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          nodegithub-version: 20

      - name: Install dependencies
        run: npm install

      - name: Build Electron package
        run: npm run build
        env:
          GH_TOKEN: ${{ secrets.RELEASE_TOKEN }}

  release:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Publish release
        if: ${{ startsWith(github.ref, 'refs/tags/v') }}
        run: gh release edit ${{ github.ref_name }} --draft=false
        env:
          GH_TOKEN: ${{ secrets.RELEASE_TOKEN }}

      # - name: Extract tag name
      #   id: tag
      #   run: echo "::set-output name=tag_name::${GITHUB_REF#refs/tags/v}"

      # - name: Create release
      #   uses: softprops/action-gh-release@v1
      #   if: startsWith(github.ref, 'refs/tags/')
      #   with:
      #     token: ${{ secrets.RELEASE_TOKEN }}
      #     files: |
      #       ./release/${{ steps.tag.outputs.tag_name }}/Video2Blog-Windows-${{ steps.tag.outputs.tag_name }}-Setup.exe
      #       ./release/${{ steps.tag.outputs.tag_name }}/Video2Blog-Mac-${{ steps.tag.outputs.tag_name }}-Install.dmg